"""Add cascade delete for wrestler_id

Revision ID: f25c5f871a12
Revises: 9d58c351550e
Create Date: 2025-04-19 13:41:56.258431

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f25c5f871a12'
down_revision: Union[str, None] = '9d58c351550e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('wrestlerstats_ibfk_1', 'wrestlerstats', type_='foreignkey')
    op.create_foreign_key(None, 'wrestlerstats', 'wrestler', ['wrestler_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'wrestlerstats', type_='foreignkey')
    op.create_foreign_key('wrestlerstats_ibfk_1', 'wrestlerstats', 'wrestler', ['wrestler_id'], ['id'])
    # ### end Alembic commands ###
