version: '3.8'

services:
  auth-db:
    image: postgres:13
    volumes:
      - auth-db-data:/var/lib/postgresql/data 
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=auth_db 
    ports:
      - "5432:5432"
    networks:
      - ranking-wrestlers-network

  
  auth-service:
    build: 
      context: ./services/auth 
    depends_on:
      - auth-db
    environment:
      - DATABASE_URI=postgresql://postgres:postgres@auth-db/auth_db
      - SECRET_KEY=my-secret-key
    ports:
      - "8000:8000"
    networks:
      - ranking-wrestlers-network
    volumes:
      - ./services/auth:/app
    command: sh -c "while ! nc -z auth-db 5432; do sleep 1; done; uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"

  wrestlers-db:
    image: postgres:13
    volumes:
      - wrestlers-db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=wrestlers
    ports:
      - "5433:5432"
    networks:
      - ranking-wrestlers-network

  wrestlers-service:
    build: 
      context: ./services/wrestlers
    depends_on:
      - wrestlers-db
      - auth-service
    environment:
      - DATABASE_URI=postgresql://postgres:postgres@wrestlers-db/wrestlers
      - AUTH_SERVICE_URL=http://auth-service:8000
    ports:
      - "8001:8001"
    networks:
      - ranking-wrestlers-network
    volumes:
      - ./services/wrestlers:/app
    command: sh -c "while ! nc -z wrestlers-db 5432; do sleep 1; done; uvicorn app.main:app --host 0.0.0.0 --port 8001 --reload"

  matches-db:
    image: postgres:13 
    volumes:
      - matches-db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=matches 
    ports:
      - "5434:5432"
    networks:
      - ranking-wrestlers-network

  matches-service:
    build:
      context: ./services/matches
    depends_on:
      - matches-db 
      - auth-service
      - wrestlers-service 
      - events-service 
    environment:
      - DATABASE_URI=postgresql://postgres:postgres@events-db/events 
      - AUTH_SERVICE_URL=http://auth-service:8000
      - WRESTLER_SERVICE_URL=http://wrestlers-service:8001
      - EVENTS_SERVICE_URL=http://events-service:8003
    ports:
      - "8002:8002"
    networks:
      - ranking-wrestlers-network
    volumes:
      - ./services/matches:/app
    command: sh -c "while ! nc -z matches-db 5432; do sleep 1; done; uvicorn app.main:app --host 0.0.0.0 --port 8002 --reload"


  events-db:
    image: postgres:13
    volumes:
      - events-db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=events
    ports:
      - "5435:5432"
    networks:
      - ranking-wrestlers-network

  events-service:
    build: 
      context: ./services/events 
    depends_on:
      - events-db 
      - auth-service
    environment:
      - DATABASE_URI=postgresql://postgres:postgres@events-db/events 
      - AUTH_SERVICE_URL=http://auth-service:8000
    ports:
      - "8003:8003"
    networks:
      - ranking-wrestlers-network
    volumes:
      - ./services/events:/app
    command: sh -c "while ! nc -z events-db 5432; do sleep 1; done; uvicorn app.main:app --host 0.0.0.0 --port 8003 --reload"
    
networks:
  ranking-wrestlers-network:
    driver: bridge

volumes:
  auth-db-data:
  wrestlers-db-data:
  matches-db-data:
  events-db-data:

